# -*- coding: utf-8 -*-
"""wuzzuf-scraping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pWdTZTTLykEGxvMbA-0aF4ZC31dvhDUV

# **Wuzzuf.net Scraping**
"""

# Commented out IPython magic to ensure Python compatibility.
# importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline
sns.set()

# libraries for scraping
from bs4 import BeautifulSoup
from urllib.request import urlopen

# requied url
url = 'https://wuzzuf.net/search/jobs/?q=data+analyst&a=hpb'

client = urlopen(url)

html = client.read()

client.close()

"""## Creating the soup"""

soup = BeautifulSoup(html, 'lxml')

"""## Getting the page title"""

soup.find("title").text

"""## Creating the containers"""

containers = soup.find_all("div", {"class":"css-1gatmva e1v1l3u10"})

len(containers)

"""### Accessing page elements"""

# Creating empty list to store jobs_details
jobs = []

for job in containers:
  job_title = job.find("h2", {'class':'css-m604qf'}).text
  company_name = job.find("a", {'class':'css-17s97q8'}).text[:-2]
  company_location = job.find("span", {'class':'css-5wys0k'}).text
  job_type = job.find("span",{'class':'css-1ve4b75 eoyjyou0'}).text
  level = job.find('div', {'class':'css-y4udm8'}).find_all("a", {'class':'css-o171kl'})[0].text
  if level != 'Not specified':
    experience = job.find('div', {'class':'css-y4udm8'}).find_all('div')[1].find("span").text.replace('Yrs of Exp', " ").replace('· ', " ").strip()
  else:
    experience = None
  job_details = {'Job_title':job_title, 'Company_name':company_name, 'Company_location':company_location, 'Job_type':job_type, 'Level':level, "Years_of_exp":experience}
  jobs.append(job_details)

df = pd.DataFrame(jobs)

df.to_excel('data_analyst_jobs.xlsx', index=False)

"""# **Created by :**
## Mohamed Ayman
## **Contact us:** +20 1090443886
"""